---
name: Yaml Lint Release Notes Pull Request
on:
  - push
  # pull_request:
  #   paths:
  #     - releases/**/release-notes/**.yaml
  # Allow manual triggering
  # workflow_dispatch: {}

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  yaml-lint-checker:
    name: Release Notes Check Yaml 👀
    runs-on: ubuntu-22.04
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Check out code
        uses: actions/checkout@v4
      - name: Fetch master branch
        run: git fetch origin master:master
      - name: Set up Python environment
        run: |
          python3 -m venv lint-env
          source lint-env/bin/activate
          pip install -r .github/scripts/requirements.txt
      - name: Validate YAML
        id: validate_yaml
        run: |
          #!/usr/bin/env bash
          set -Eeuo pipefail
          git branch 
          python --version
          source lint-env/bin/activate
          echo "venv $VIRTUAL_ENV"
          pip list 
          git diff --name-only --name-only $(git merge-base origin/master HEAD) -- releases/
          CHANGED_FILES=$(git diff --name-only --name-only $(git merge-base origin/master HEAD) -- releases/ | grep -E '\.ya?ml$' || true)
          echo "CHANGED_FILES $CHANGED_FILES"
          if [ -n "$CHANGED_FILES" ]; then
            echo "Validating yaml files $CHANGED_FILES"
            python .github/scripts/validate_yaml.py $CHANGED_FILES
          else 
            echo "No YAML files changed under /releases/*"
          fi
          deactivate
